inline operator fun UByteArray.get(i: UInt) = get(i.toInt())
inline operator fun UByteArray.set(i: UInt, v: UByte) = set(i.toInt(), v)
inline operator fun UByteArray.get(i: UShort) = get(i.toInt())
inline operator fun UByteArray.set(i: UShort, v: UByte) = set(i.toInt(), v)
inline operator fun UByteArray.get(i: UByte) = get(i.toInt())
inline operator fun UByteArray.set(i: UByte, v: UByte) = set(i.toInt(), v)

inline operator fun UShortArray.get(i: UInt) = get(i.toInt())
inline operator fun UShortArray.set(i: UInt, v: UShort) = set(i.toInt(), v)
inline operator fun UShortArray.get(i: UShort) = get(i.toInt())
inline operator fun UShortArray.set(i: UShort, v: UShort) = set(i.toInt(), v)
inline operator fun UShortArray.get(i: UByte) = get(i.toInt())
inline operator fun UShortArray.set(i: UByte, v: UShort) = set(i.toInt(), v)

inline operator fun BooleanArray.get(i: UInt) = get(i.toInt())
inline operator fun BooleanArray.set(i: UInt, v: Boolean) = set(i.toInt(), v)
inline operator fun BooleanArray.get(i: UShort) = get(i.toInt())
inline operator fun BooleanArray.set(i: UShort, v: Boolean) = set(i.toInt(), v)
inline operator fun BooleanArray.get(i: UByte) = get(i.toInt())
inline operator fun BooleanArray.set(i: UByte, v: Boolean) = set(i.toInt(), v)
